// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// Println provides a mock function with given fields: args
func (_m *Factory) Println(args ...string) {
	_va := make([]interface{}, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
